### ISSUE TITLE
windows build

### ISSUE THREAD

**Issue by PeterMitrano** [wpilibsuite/ntcore#1]
After a quick replacement of constexpr with const, I think I've found the move constructor things you meant. Build output is [here](https://gist.github.com/PeterMitrano/ee080cefdee6832fd68b). Not sure how to move forward on this one, but hey, it made it 20% through! :+1:

**Comment by PeterJohnson** [comment]
Fixed constexpr in 3cd3d16 and 8bbe5f9.
Fixed atomic construction issue in 6b2fb02 and 0979c1c
