### ISSUE TITLE
Cannot switch back to NT3 mode after connecting to NT2 server

### ISSUE THREAD

**Issue by virtuald** [wpilibsuite/ntcore#142]
See dispatcher implementation, m_reconnect_proto_rev never gets set back to 0x0300.

**Comment by virtuald** [comment]
I fixed this in pynetworktables by immediately setting the reconnect version to 0x0300 after calling connection.set_proto_rev().

**Comment by PeterJohnson** [comment]
Oh, I like that solution better.  I'll change #143 to use that approach.
