### ISSUE TITLE
Unable to compile with cmake on linux

### ISSUE THREAD

**Issue by aldrouil** [wpilibsuite/ntcore#167]
Using CMake on linux I get the following build errors

ntcore/test/rpc_local.cpp:8:29: error: unknown type name
      'ConnectionInfo'; did you mean 'nt::ConnectionInfo'?
                      const ConnectionInfo& conn_info) {
                            ^~~~~~~~~~~~~~
                            nt::ConnectionInfo

and 

ntcore/test/rpc_speed.cpp:9:29: error: unknown type name
      'ConnectionInfo'; did you mean 'nt::ConnectionInfo'?
                      const ConnectionInfo& conn_info) {
                            ^~~~~~~~~~~~~~
                            nt::ConnectionInfo

The compilation succeeds when I manually change the referenced lines to what the compiler suggests.

This error occurs on Ubuntu 16.04 using openjdk-8 on both a armhf device and on an x86_64 pc. Both devices compiled the code natively. No cross compilation was attempted.

**Comment by 333fred** [comment]
We don't regularly use the CMake build, so I'm not surprised something broke. @PeterJohnson is looking at it, but I'd suggest using Gradle as that should work just fine (at least on PC).
