### ISSUE TITLE
Access Violation

### ISSUE THREAD

**Issue by balloman** [wpilibsuite/ntcore#188]
Whenever I call any function from the Network Tables library, I get this Access Exception error. Why is this happening, and how can I fix it.
`Unhandled exception at 0x00A90000 in NTTest.exe: 0xC0000005: Access violation executing location 0x00A90000. occurred`

**Comment by bradamiller** [comment]
Can you post the zip of a small project that does that?

**Comment by balloman** [comment]
```
// NTTest.cpp : Defines the entry point for the console application.
//

#include<iostream>
#include "stdafx.h"
#include "ntcore.h"
#include "networktables\NetworkTable.h"
#include <string>

using std::shared_ptr;

shared_ptr<NetworkTable> startConnection() {
	NetworkTable::SetClientMode();
	NetworkTable::SetIPAddress("localhost");
	shared_ptr<NetworkTable> myTable = NetworkTable::GetTable("SmartDashboard");
	return myTable;
}

int main()
{
	shared_ptr<NetworkTable> table = startConnection();
    return 0;
}
```
There you go.
As soon as I call setClientMode();, I get an exception

**Comment by bradamiller** [comment]
Didn't realize it was a PC program. Can you let us know what version of Visual Studio your are running and where you got the network tables libraries.

**Comment by balloman** [comment]
I had a mentor fix it, he mentioned something about the ntcore code never exporting the networktables or something.
