### ISSUE TITLE
Maven Central Repository

### ISSUE THREAD

**Issue by JLLeitschuh** [wpilibsuite/ntcore#20]
Would you be so kind as to publish this to the Maven Central Repository so that we can use it in our project.
https://github.com/WPIRoboticsProjects/GRIP
Or are you open to a PR that adds this?

**Comment by 333fred** [comment]
Jonathan, I don't know as though we will ever want to publish this to maven central. We aren't currently with the rest of wpilib. Is there any reason that you can't use a local publish for this?

**Comment by PeterJohnson** [comment]
This project is quite general purpose (unlike WPILib, it is not specific to FIRST and has no RoboRIO or FIRST-specific dependencies), so I can see the argument for publishing it in central repositories such as Maven.  However, I think we should move the repository from my user account to either a GitHub organization or to usfirst.collab.net before we do that type of publish... we should talk to Brad about what makes sense.

**Comment by JLLeitschuh** [comment]
Yes, we are using Travis-CI for our continuous integration. Since travis is running out on the cloud there is no way to do a local install.

**Comment by PeterJohnson** [comment]
Maven publish info committed in 75358e6c45805e709ff594e1bc6cbb96cbd7205c.

**Comment by JLLeitschuh** [comment]
I'm not seeing it on maven central.
http://search.maven.org/#search%7Cga%7C1%7Cwpi
Also, there is an organization that may be appropriate to hand this off to.
https://github.com/WPIRoboticsProjects

**Comment by 333fred** [comment]
You wouldn't. This publishes to the local maven repository, not to Maven central. Also, this is now effectively a mirror of the version on collabnet.

**Comment by JLLeitschuh** [comment]
Is there a repository that I can point gradle at to download the artifact into our project?

**Comment by 333fred** [comment]
Not currently. We're still working on the multi-platform build. For now, what I would suggest is running the publishToMavenLocal task, that will publish it to your local maven repository. Still requires you to checkout the project, but better than nothing.

**Comment by JLLeitschuh** [comment]
I can't build on my local machine (doesn't work on a mac) and I can't get Travis CI to do that either.

**Comment by 333fred** [comment]
Mac is a known issue. What's the problem with Travis? I can't help if I can't see a log.

**Comment by JLLeitschuh** [comment]
I would have to setup Travis to download and  build the Ntcore project
every time we wanted to run our build. That would also require that we had
the jdk for Linux arm downloaded automatically for every build.
Travis generates fresh virtual machine for every build. Setting up up
things so ntcore would be persistent would take more time.

**Comment by 333fred** [comment]
We've incorporated the headers into the project, so downloading the jdk is no longer required.

**Comment by 333fred** [comment]
ntcore is now published to the FRC Maven repo. See the README for the artifact identifiers.
