### ISSUE TITLE
ARM JDK Download Script

### ISSUE THREAD

**Issue by JLLeitschuh** [wpilibsuite/ntcore#24]
The ARM JDK can automatically be downloaded using the following script:

```
wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/8u60-b27/jdk-8u60-linux-arm64-vfp-hflt.tar.gz"
```

It would be a simple fix to add this to the build with an untar command and the install would be totally automated.

Also, the link in the gradle script is out of date.

**Comment by 333fred** [comment]
You are correct about the link being out of date. However, this script is not something we can do. This directly violates Oracle's terms of service.
