### ISSUE TITLE
NetworkTableEntry.callRpc is package-private

### ISSUE THREAD

**Issue by Ro5bert** [wpilibsuite/ntcore#276]
I'm trying to use the builtin RPC functionality in the Java WPI library, but there seems to be no proper way to initiate an RPC. The only way that seems to work would be direct instantiation of an `RpcCall` object with a call handle received from calling `callRpc` on `NetworkTablesJNI`, but that's not recommended in the constructor documentation for `RpcCall`. `NetworkTablesEntry.callRpc` seems like the obvious answer, but it's package-private making it inaccessible to user code. Also, my IDE (Intellij) cannot find any usages of `NetworkTableEntry.callRpc` in the WPI library, which leads me to believe it is meant to be used in user code which would imply its current access modifier is a bug. (I'll also point out a similar problem exists with `NetworkTableEntry.createRpc`, but this can be circumnavigated with `NetworkTableInstance.createRpc`.) Is this intentional? If so, how should one initiate an RPC?

**Comment by PeterJohnson** [comment]
You're right, those functions were not intended to be package-private.
