### ISSUE TITLE
Error compiling ntcore for windows x64

### ISSUE THREAD

**Issue by ebot1234** [wpilibsuite/ntcore#279]
Hi,
So I was trying to build the ntcore library for windows x64 through command prompt. I keep getting the no tool chain found error and then build fail. I have Visual Studio build tools and VS Studio Community for Visual C++ installed. Any thoughts on how I can get this to build.
Thanks,
Ethen

**Comment by PeterJohnson** [comment]
This repo is no longer maintained, as ntcore has been integrated into the allwpilib repo.  The allwpilib repo has both gradle and cmake options for building.  If you have issues building there please open an issue on that repo.
