### ISSUE TITLE
SetTeam still uses old cRIO address

### ISSUE THREAD

**Issue by ThadHouse** [wpilibsuite/ntcore#35]
Why does the SetTeam function still use the 10.xx.xx.2 ip address? Since ntcore does not compile for cRIO currently, it seems like there is no point in keeping the SetTeam function using the IP address. I had to help a few teams last year fix their dashboards because they were setting to the old IP that wasn't valid anymore. Usually it seems like the RoboRIO gets an IP of 10.xx.xx.20, but because of Mdns it could be random. Should SetTeam be changed to use Mdns instead? 

I have a pull request ready for this, but wanted to discuss it first.

**Comment by PeterJohnson** [comment]
Yes, SetTeam should use mdns.  Thanks.
