### ISSUE TITLE
Allow for disabling of tests

### ISSUE THREAD

**Issue by nekoknot** [wpilibsuite/ntcore#38]
If you're including the project elsewhere, it's not really necessary to build the test cases. It would be nice to have a flag to disable building them.

**Comment by 333fred** [comment]
Do you mean via cmake or gradle?

**Comment by nekoknot** [comment]
cmake

**Comment by 333fred** [comment]
That's more @PeterJohnson, I do the gradle stuff. I could add a similar switch to the gradle build though.

**Comment by nekoknot** [comment]
Wouldn't hurt, if it's not too much of a hassle. Just because I don't use gradle doesn't mean someone else won't.
