### ISSUE TITLE
Cannot build without x86 headers on linux?

### ISSUE THREAD

**Issue by virtuald** [wpilibsuite/ntcore#43]
Would be nice if there were a `-PskipX86` flag.

**Comment by 333fred** [comment]
Are you trying to just build, or publish as well? If it's just build, run a `./gradlew :native:tasks` to see how to build just the x64 stuff.

**Comment by virtuald** [comment]
I'm trying to build outline viewer, presumably I have to publish for it to get the upstream.

**Comment by PeterJohnson** [comment]
Fixed by #210.
