### ISSUE TITLE
Naming for new atomic get set operation

### ISSUE THREAD

**Issue by ThadHouse** [wpilibsuite/ntcore#53]
In the past, SmartDashboard has always had the issue where you had to put a number to the dashboard before you could read it and change values from the SmartDashboard. Most teams I know would just run a bunch of Put**\* calls in RobotInit, that would write safe defaults, and then could be safely read from robot code and edited from the dashboard. However, the addition of persistent entries has made this a much harder task. The Put calls in RobotInit are no longer safe, as they very likely will override the value read from persistent. We've had this happen to us, where we set values persistent, run testing for an hour, and then when we reboot all the persistent values are overridden because we forgot to remove the put calls in RobotInit. I thought about first reading to check if the key exists, and only putting if it does not, however that's not thread safe, and the SmartDashboard class in WPILib does not have a built in method to check if key exists (I plan on pushing some patches to WPILib later to add some of the new NT3 functionality).

I have been working on an atomic operation to first check if the key exists, returning the value in the table if it does, otherwise setting the table to a passed in value, and then returning that. I think I have the code working, and wrote working tests, however I don't really know what a good name for a method like that would be. Currently I have it set to `GetSetEntryValue`, however that doesn't sound right, and I can't come up with anything better. Any ideas? Also do you think this would be a valid addition? You can see the code here https://github.com/ThadHouse/ntcore/commit/9f2de773cddf151bbab5f05692806ef9ab2159bc

**Comment by PeterJohnson** [comment]
In Python dictionaries, this type of operation is called SetDefault.   "setdefault(key, default): If key is in the dictionary, return its value. If not, insert key with a value of default and return default."  Yes, I think this is a valid addition.
