### ISSUE TITLE
Memory leak on NetworkTable::AddTableListener/NetworkTable::RemoveTableListener

### ISSUE THREAD

**Issue by xeniarose** [wpilibsuite/ntcore#80]
Test code:

``` c++
class BasicListener : public ITableListener {
    void ValueChanged(ITable* source,
        llvm::StringRef key,
        std::shared_ptr<nt::Value> value,
        bool isNew) {
    }
};

int main() {
    system("PAUSE");
    NetworkTable::SetServerMode();
    NetworkTable::Initialize();

    std::shared_ptr<NetworkTable> ptr = NetworkTable::GetTable("SmartDashboard");
    BasicListener* bl = new BasicListener();

    for (int i = 0; i < 1000000; i++) {     
        ptr->AddTableListener(bl);
        ptr->RemoveTableListener(bl);
    }

    NetworkTable::Shutdown();
    delete bl;

    system("PAUSE");
    return 0;
}
```

At the second pause, memory usage is over 100MB.

I did some digging into this issue. Looking at `Notifier::RemoveEntryListener`, it doesn't ever delete from `m_entry_listeners`

![](http://image.prntscr.com/image/4bce29b090b64df282719d5dd4ff9724.png)

From first glance it looks like "uids" are dependant on the ordering of the vector and that's why entry listeners are never deleted. Perhaps `m_entry_listeners` would be better as a `std::unordered_map` or `std::map`

**Comment by PeterJohnson** [comment]
Note the solution in #81 won't always result in freeing all memory used (e.g. if you create 10000 notifiers and then delete them, it will still have 10000 notifiers allocated).
